[FileDialog]
history=file:///home/clem/Cloud/Pictures/Screenshots, file:///home/clem/Cloud/CalPoly/Wolfram Mathematica, file:///home/clem/Documents, file:///run/media/clem/SANKESU/CalPoly/Wolfram Mathematica, file:///home/clem
lastVisited=file:///home/clem/Cloud/CalPoly/Wolfram Mathematica
qtVersion=5.15.2
shortcuts=file:, file:///home/clem, file:///home/clem/Cloud, file:///home/clem/Cloud/CalPoly/Wolfram Mathematica
sidebarWidth=82
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xb2\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xe1\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x38\0\0\0\x1\0\0\0\0\0\0\0\x61\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
